import '../../assets/css/general.css'
import './styles.css'
import 'flickity/dist/flickity.min.css'

import 'icons/user.svg'
import 'icons/hoja1.svg'
import 'icons/hoja2.svg'
import 'icons/hoja3.svg'
import 'icons/hoja4.svg'
import 'icons/hoja5.svg'
import 'icons/hoja6.svg'
import 'icons/hoja7.svg'
import 'icons/hoja8.svg'
import 'icons/hoja9.svg'
import 'icons/hoja10.svg'
import 'icons/hoja11.svg'
import 'icons/hoja12.svg'
import 'icons/hoja13.svg'
import 'icons/plantin.svg'
import 'icons/lugar.svg'
import 'icons/info.svg'
import 'icons/calendar.svg'
import 'icons/calendar.11.svg'
import 'icons/reloj.svg'
import 'icons/arrow.left.svg'
import 'icons/social.facebook.svg'
import 'icons/social.twitter.svg'
import 'icons/social.google.svg'
import 'icons/caret.right.svg'
import 'icons/plantin.solo.svg'
import 'icons/plantines.svg'
import 'icons/plantines2.svg'
import 'icons/github.svg'

import html from './index.html'

import Page from 'page'
import 'components/svg-icon'
import 'components/form-vali'
import 'components/pop-up'
import 'components/h-tabs'
import 'components/side-bar'
import 'components/geo-map'
import actions from './actions'
import renders from './renders'

Page('home', html, {actions, renders})
