import './styles.css'
import 'icons/calendar.11.svg'
import 'icons/mas.svg'
import 'icons/social.facebook.svg'
import 'icons/close.svg'
import 'icons/lugar.svg'
import 'icons/reloj.svg'
import 'icons/caret.right.svg'
import 'icons/caret.left.svg'
import 'components/slider-box'
import Component from 'component'
import renders from './renders'
import actions from './actions'

Component('event-pop', {actions, renders})
