import '../../assets/css/general.css'
import './styles.css'

import 'icons/user.svg'
import 'icons/arboles.Aliso.svg'
import 'icons/arboles.Caranday.svg'
import 'icons/arboles.Chica.svg'
import 'icons/arboles.Sen.svg'
import 'icons/arboles.Algarrobo.svg'
import 'icons/arboles.Ceibo.svg'
import 'icons/arboles.Vinal.svg'
import 'icons/arboles.Tala.svg'
import 'icons/arboles.Sombra.svg'
import 'icons/arboles.Curupay.svg'
import 'icons/arboles.Chal.svg'
import 'icons/arboles.Brea.svg'
import 'icons/arboles.Coronillo.svg'
import 'icons/plantin.svg'
import 'icons/lugar.svg'
import 'icons/info.svg'
import 'icons/salir.svg'
import 'icons/arrow.left.svg'
import 'icons/social.facebook.svg'
import 'icons/social.twitter.svg'
import 'icons/social.google.svg'

import html from './index.html'

import Page from 'page'
import 'components/svg-icon'
import 'components/form-vali'
import 'components/pop-up'
import 'components/side-bar'
import 'components/geo-map'
import 'components/scroll-items'
import actions from './actions'
import renders from './renders'

Page('home', html, {actions, renders})
